services:
  database:
    image: postgres:15-alpine
    container_name: postgres_db
    env_file: ./docker/postgres.env
    # Pas besoin de ports ici si on n'utilise que PgAdmin pour voir la DB
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build:
      context: .
      dockerfile: ./docker/backend.dockerfile
    container_name: backend_app
    env_file: ./docker/backend.env
    ports:
      - "3000:3000"  # <--- Ouvre la porte du Backend
    depends_on:
      - database
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.dockerfile
    container_name: frontend_app
    env_file: ./docker/frontend.env
    ports:
      - "5173:5173"  # <--- Ouvre la porte du Frontend
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    env_file: ./docker/pgadmin.env
    ports:
      - "8080:80"    # <--- Utilise 8080 pour éviter les conflits avec le système
    volumes:
      - ./docker/pgadmin_servers.json:/pgadmin4/servers.json
    depends_on:
      - database
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data: