services:
  tor:
    image: dperson/torproxy
    container_name: tor
    environment:
      - LOCATION=FR
      - TOR_MaxCircuitDirtiness=600

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - tor
    # On n'a plus besoin d'exposer le port 5000 au public !
    # Seul Nginx y acc√©dera en interne.

  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - ./frontend/index.html:/usr/share/nginx/html/index.html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - backend